### ISSUE TITLE
Executável/App

### ISSUE THREAD

**Issue by rodreras** [Patotricks15/Robo_sigaa#1]
Projetinho legal. Já dá pra gente pensar em fazer um executável ou então um app hahaha

**Comment by Patotricks15** [comment]
Valeu, Brust! 😄  Pensei em fazer mesmo, mas ainda não consegui fazer o selenium rodar "por baixo dos panos". Fica aí pra um futuro não mt distante kkkk

**Comment by rodreras** [comment]
Posso te ajudar com streamlit. É bem de boa. Depois conversamos mais. Vou fechar esse "issue" haha
